version: 0.2

env:
  FILE_FORMAT: ${FILEFORMAT}

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.8
    commands:
      - env
  pre_build:
    commands:
      - echo Starting Docker daemon

  build:
    commands:
      - ls -al
reports:
  tests-coverage:
    files:
      - '**/*'
    base-directory: '/'
    file-format: $FILE_FORMAT
